//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIS.Law.WebServiceInterfaces
{
    using System.Runtime.Serialization;
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfBankSearchItemm9nI5F_S7", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfBankSearchItemm9nI5F_S7 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Bank.BankSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Bank.BankSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
}
namespace IRIS.Law.WebServiceInterfaces.Bank
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Bank")]
    public partial class BankSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {
        
        private int BankSearchTypesField;
        
        private bool IncludeArchivedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BankSearchTypes
        {
            get
            {
                return this.BankSearchTypesField;
            }
            set
            {
                this.BankSearchTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeArchived
        {
            get
            {
                return this.IncludeArchivedField;
            }
            set
            {
                this.IncludeArchivedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Bank")]
    public partial class BankSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfBankSearchItemm9nI5F_S7 BanksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfBankSearchItemm9nI5F_S7 Banks
        {
            get
            {
                return this.BanksField;
            }
            set
            {
                this.BanksField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Bank")]
    public partial class BankSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BankIdField;
        
        private int BankTypeIdField;
        
        private string DescriptionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BankId
        {
            get
            {
                return this.BankIdField;
            }
            set
            {
                this.BankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BankTypeId
        {
            get
            {
                return this.BankTypeIdField;
            }
            set
            {
                this.BankTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
}
//namespace IRIS.Law.PmsCommonData
//{
//    using System.Runtime.Serialization;
    
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="DataConstants.BankSearchTypes", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.PmsCommonData")]
//    public enum DataConstantsBankSearchTypes : int
//    {
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        All = 0,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Client = 1,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Office = 2,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        Deposit = 3,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        ClientOffice = 4,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        ClientDeposit = 5,
        
//        [System.Runtime.Serialization.EnumMemberAttribute()]
//        OfficeDeposit = 6,
//    }
//}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBankService")]
public interface IBankService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/BankSearch", ReplyAction="http://tempuri.org/IBankService/BankSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Bank.BankSearchReturnValue BankSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Bank.BankSearchCriteria criteria);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBankServiceChannel : IBankService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BankServiceClient : System.ServiceModel.ClientBase<IBankService>, IBankService
{
    
    public BankServiceClient()
    {
    }
    
    public BankServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public IRIS.Law.WebServiceInterfaces.Bank.BankSearchReturnValue BankSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Bank.BankSearchCriteria criteria)
    {
        return base.Channel.BankSearch(logonId, collectionRequest, criteria);
    }
}
