//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIS.Law.WebServiceInterfaces
{
    using System.Runtime.Serialization;


   
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataListOfDiaryMemberSearchItemKvbnOJxc", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfDiaryMemberSearchItemKvbnOJxc : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int FirstRowNumberField;

        private IRIS.Law.WebServiceInterfaces.Diary.DiaryMemberSearchItem[] RowsField;

        private int TotalRowCountField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Diary.DiaryMemberSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataListOfAppointmentKvbnOJxc", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfAppointmentKvbnOJxc : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int FirstRowNumberField;

        private IRIS.Law.WebServiceInterfaces.Diary.Appointment[] RowsField;

        private int TotalRowCountField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Diary.Appointment[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataListOfCancellationCodeSearchItemKvbnOJxc", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfCancellationCodeSearchItemKvbnOJxc : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int FirstRowNumberField;

        private IRIS.Law.WebServiceInterfaces.Diary.CancellationCodeSearchItem[] RowsField;

        private int TotalRowCountField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Diary.CancellationCodeSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataListOfTaskKvbnOJxc", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfTaskKvbnOJxc : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int FirstRowNumberField;

        private IRIS.Law.WebServiceInterfaces.Diary.Task[] RowsField;

        private int TotalRowCountField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Diary.Task[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataListOfDiaryParameterSearchItemKvbnOJxc", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfDiaryParameterSearchItemKvbnOJxc : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int FirstRowNumberField;

        private IRIS.Law.WebServiceInterfaces.Diary.DiaryParameterSearchItem[] RowsField;

        private int TotalRowCountField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Diary.DiaryParameterSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }

    
}
namespace IRIS.Law.WebServiceInterfaces.Diary
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AppointmentReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class AppointmentReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.Diary.Appointment AppointmentField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Diary.Appointment Appointment
        {
            get
            {
                return this.AppointmentField;
            }
            set
            {
                this.AppointmentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AppointmentSearchReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class AppointmentSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.DataListOfAppointmentKvbnOJxc AppointmentsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfAppointmentKvbnOJxc Appointments
        {
            get
            {
                return this.AppointmentsField;
            }
            set
            {
                this.AppointmentsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CancellationCodeSearchReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class CancellationCodeSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.DataListOfCancellationCodeSearchItemKvbnOJxc CancellationCodesField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfCancellationCodeSearchItemKvbnOJxc CancellationCodes
        {
            get
            {
                return this.CancellationCodesField;
            }
            set
            {
                this.CancellationCodesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TaskSearchReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class TaskSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.DataListOfTaskKvbnOJxc TasksField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfTaskKvbnOJxc Tasks
        {
            get
            {
                return this.TasksField;
            }
            set
            {
                this.TasksField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DiaryParameterReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class DiaryParameterReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.DataListOfDiaryParameterSearchItemKvbnOJxc DiaryParamtersField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfDiaryParameterSearchItemKvbnOJxc DiaryParamters
        {
            get
            {
                return this.DiaryParamtersField;
            }
            set
            {
                this.DiaryParamtersField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TaskReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class TaskReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.Diary.Task TaskField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Diary.Task Task
        {
            get
            {
                return this.TaskField;
            }
            set
            {
                this.TaskField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DiaryMemberSearchReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class DiaryMemberSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.DataListOfDiaryMemberSearchItemKvbnOJxc DiaryMembersField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfDiaryMemberSearchItemKvbnOJxc DiaryMembers
        {
            get
            {
                return this.DiaryMembersField;
            }
            set
            {
                this.DiaryMembersField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Appointment", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class Appointment : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AttendeesField;

        private string AttendeesNameField;

        private string DurationField;

        private string EndTimeField;

        private int IdField;

        private string IsEditableField;

        private bool IsReminderSetField;

        private string NotesField;

        private System.Guid ProjectIdField;

        private string ReminderBeforeTimeField;

        private System.DateTime ReminderDateField;

        private string ReminderTimeField;

        private string ReminderTypeField;

        private System.DateTime StartDateField;

        private string StartTimeField;

        private string SubjectField;

        private System.Guid VenueIdField;

        private string VenueTextField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attendees
        {
            get
            {
                return this.AttendeesField;
            }
            set
            {
                this.AttendeesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttendeesName
        {
            get
            {
                return this.AttendeesNameField;
            }
            set
            {
                this.AttendeesNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsEditable
        {
            get
            {
                return this.IsEditableField;
            }
            set
            {
                this.IsEditableField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReminderSet
        {
            get
            {
                return this.IsReminderSetField;
            }
            set
            {
                this.IsReminderSetField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReminderBeforeTime
        {
            get
            {
                return this.ReminderBeforeTimeField;
            }
            set
            {
                this.ReminderBeforeTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReminderDate
        {
            get
            {
                return this.ReminderDateField;
            }
            set
            {
                this.ReminderDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReminderTime
        {
            get
            {
                return this.ReminderTimeField;
            }
            set
            {
                this.ReminderTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReminderType
        {
            get
            {
                return this.ReminderTypeField;
            }
            set
            {
                this.ReminderTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid VenueId
        {
            get
            {
                return this.VenueIdField;
            }
            set
            {
                this.VenueIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueText
        {
            get
            {
                return this.VenueTextField;
            }
            set
            {
                this.VenueTextField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CancellationCodeSearchItem", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class CancellationCodeSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodeField;

        private string DescriptionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Task", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AttendeesField;

        private string AttendeesNameField;

        private System.DateTime CompletedDateField;

        private System.DateTime DueDateField;

        private int IdField;

        private bool IsCompletedField;

        private string IsEditableField;

        private bool IsLimitationTaskField;

        private bool IsPublicField;

        private string MattersField;

        private string NotesField;

        private string ProgressField;

        private System.Guid ProjectIdField;

        private string RecordedDueDateField;

        private string StatusDescField;

        private int StatusIdField;

        private string SubjectField;

        private int TypeIdField;

        private bool IsPrivateField;

        private bool IsReminderSetField;

        private string ReminderBeforeTimeField;

        private System.DateTime ReminderDateField;

        private string ReminderTimeField;

        private string ReminderTypeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attendees
        {
            get
            {
                return this.AttendeesField;
            }
            set
            {
                this.AttendeesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttendeesName
        {
            get
            {
                return this.AttendeesNameField;
            }
            set
            {
                this.AttendeesNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompletedDate
        {
            get
            {
                return this.CompletedDateField;
            }
            set
            {
                this.CompletedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompleted
        {
            get
            {
                return this.IsCompletedField;
            }
            set
            {
                this.IsCompletedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsEditable
        {
            get
            {
                return this.IsEditableField;
            }
            set
            {
                this.IsEditableField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLimitationTask
        {
            get
            {
                return this.IsLimitationTaskField;
            }
            set
            {
                this.IsLimitationTaskField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublic
        {
            get
            {
                return this.IsPublicField;
            }
            set
            {
                this.IsPublicField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matters
        {
            get
            {
                return this.MattersField;
            }
            set
            {
                this.MattersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Progress
        {
            get
            {
                return this.ProgressField;
            }
            set
            {
                this.ProgressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecordedDueDate
        {
            get
            {
                return this.RecordedDueDateField;
            }
            set
            {
                this.RecordedDueDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                this.StatusDescField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                this.StatusIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId
        {
            get
            {
                return this.TypeIdField;
            }
            set
            {
                this.TypeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate
        {
            get
            {
                return this.IsPrivateField;
            }
            set
            {
                this.IsPrivateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReminderSet
        {
            get
            {
                return this.IsReminderSetField;
            }
            set
            {
                this.IsReminderSetField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReminderBeforeTime
        {
            get
            {
                return this.ReminderBeforeTimeField;
            }
            set
            {
                this.ReminderBeforeTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReminderDate
        {
            get
            {
                return this.ReminderDateField;
            }
            set
            {
                this.ReminderDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReminderTime
        {
            get
            {
                return this.ReminderTimeField;
            }
            set
            {
                this.ReminderTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReminderType
        {
            get
            {
                return this.ReminderTypeField;
            }
            set
            {
                this.ReminderTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DiaryParameterSearchItem", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class DiaryParameterSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DescriptionField;

        private int IdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DiaryMemberSearchItem", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class DiaryMemberSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool IsGroupField;

        private bool IsMemberField;

        private bool IsResourceField;

        private string MemberCodeField;

        private string MemberDisplayNameField;

        private string MemberIDField;

        private string MemberTypeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGroup
        {
            get
            {
                return this.IsGroupField;
            }
            set
            {
                this.IsGroupField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMember
        {
            get
            {
                return this.IsMemberField;
            }
            set
            {
                this.IsMemberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsResource
        {
            get
            {
                return this.IsResourceField;
            }
            set
            {
                this.IsResourceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberCode
        {
            get
            {
                return this.MemberCodeField;
            }
            set
            {
                this.MemberCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberDisplayName
        {
            get
            {
                return this.MemberDisplayNameField;
            }
            set
            {
                this.MemberDisplayNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberID
        {
            get
            {
                return this.MemberIDField;
            }
            set
            {
                this.MemberIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberType
        {
            get
            {
                return this.MemberTypeField;
            }
            set
            {
                this.MemberTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TaskSearchCriteria", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class TaskSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {

        private string MemberIDField;

        private System.Guid ProjectIDField;

        private System.Nullable<System.DateTime> StartDateField;

        private string StatusField;

        private System.Nullable<System.DateTime> ToDateField;

        private string OrderByField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberID
        {
            get
            {
                return this.MemberIDField;
            }
            set
            {
                this.MemberIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectID
        {
            get
            {
                return this.ProjectIDField;
            }
            set
            {
                this.ProjectIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ToDate
        {
            get
            {
                return this.ToDateField;
            }
            set
            {
                this.ToDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }

        
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AppointmentSearchCriteria", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class AppointmentSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {

        private System.Nullable<System.DateTime> DateField;

        private string MemberIDField;

        private string OrderByField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberID
        {
            get
            {
                return this.MemberIDField;
            }
            set
            {
                this.MemberIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DeleteData", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Diary")]
    public partial class DeleteData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CancellationTextField;

        private string CategoryCodeField;

        private bool IsBookingATaskField;

        private string MemberIdField;

        private int OccurenceIdField;

        private string ReasonCodeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CancellationText
        {
            get
            {
                return this.CancellationTextField;
            }
            set
            {
                this.CancellationTextField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryCode
        {
            get
            {
                return this.CategoryCodeField;
            }
            set
            {
                this.CategoryCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBookingATask
        {
            get
            {
                return this.IsBookingATaskField;
            }
            set
            {
                this.IsBookingATaskField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberId
        {
            get
            {
                return this.MemberIdField;
            }
            set
            {
                this.MemberIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OccurenceId
        {
            get
            {
                return this.OccurenceIdField;
            }
            set
            {
                this.OccurenceIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDiaryService")]
public interface IDiaryService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/GetDiaryMembers", ReplyAction = "http://tempuri.org/IDiaryService/GetDiaryMembersResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.DiaryMemberSearchReturnValue GetDiaryMembers(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/GetAppointmentDetails", ReplyAction = "http://tempuri.org/IDiaryService/GetAppointmentDetailsResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.AppointmentReturnValue GetAppointmentDetails(System.Guid logonId, int appointmentId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/AppointmentSearch", ReplyAction = "http://tempuri.org/IDiaryService/AppointmentSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.AppointmentSearchReturnValue AppointmentSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Diary.AppointmentSearchCriteria criteria);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/SaveAppointment", ReplyAction = "http://tempuri.org/IDiaryService/SaveAppointmentResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.AppointmentReturnValue SaveAppointment(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Diary.Appointment appointmentDetails);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/GetBookingCancelledReasons", ReplyAction = "http://tempuri.org/IDiaryService/GetBookingCancelledReasonsResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.CancellationCodeSearchReturnValue GetBookingCancelledReasons(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/GetBookingCancelledCategories", ReplyAction = "http://tempuri.org/IDiaryService/GetBookingCancelledCategoriesResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.CancellationCodeSearchReturnValue GetBookingCancelledCategories(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/DeleteBooking", ReplyAction = "http://tempuri.org/IDiaryService/DeleteBookingResponse")]
    IRIS.Law.WebServiceInterfaces.ReturnValue DeleteBooking(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Diary.DeleteData deleteData);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/MemberTaskSearch", ReplyAction = "http://tempuri.org/IDiaryService/MemberTaskSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.TaskSearchReturnValue MemberTaskSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Diary.TaskSearchCriteria criteria);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/MatterTaskSearch", ReplyAction = "http://tempuri.org/IDiaryService/MatterTaskSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.TaskSearchReturnValue MatterTaskSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Diary.TaskSearchCriteria criteria);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/GetTaskTypes", ReplyAction = "http://tempuri.org/IDiaryService/GetTaskTypesResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.DiaryParameterReturnValue GetTaskTypes(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/GetMemberTaskDetails", ReplyAction = "http://tempuri.org/IDiaryService/GetMemberTaskDetailsResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.TaskReturnValue GetMemberTaskDetails(System.Guid logonId, int taskId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/SaveTask", ReplyAction = "http://tempuri.org/IDiaryService/SaveTaskResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.TaskReturnValue SaveTask(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Diary.Task taskDetails);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiaryService/GetMatterTaskDetails", ReplyAction = "http://tempuri.org/IDiaryService/GetMatterTaskDetailsResponse")]
    IRIS.Law.WebServiceInterfaces.Diary.TaskReturnValue GetMatterTaskDetails(System.Guid logonId, System.Guid projectId, int taskId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDiaryServiceChannel : IDiaryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DiaryServiceClient : System.ServiceModel.ClientBase<IDiaryService>, IDiaryService
{

    public DiaryServiceClient()
    {
    }

    public DiaryServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public DiaryServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public DiaryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public DiaryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public IRIS.Law.WebServiceInterfaces.Diary.DiaryMemberSearchReturnValue GetDiaryMembers(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest)
    {
        return base.Channel.GetDiaryMembers(logonId, collectionRequest);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.AppointmentReturnValue GetAppointmentDetails(System.Guid logonId, int appointmentId)
    {
        return base.Channel.GetAppointmentDetails(logonId, appointmentId);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.AppointmentSearchReturnValue AppointmentSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Diary.AppointmentSearchCriteria criteria)
    {
        return base.Channel.AppointmentSearch(logonId, collectionRequest, criteria);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.AppointmentReturnValue SaveAppointment(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Diary.Appointment appointmentDetails)
    {
        return base.Channel.SaveAppointment(logonId, appointmentDetails);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.CancellationCodeSearchReturnValue GetBookingCancelledReasons(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest)
    {
        return base.Channel.GetBookingCancelledReasons(logonId, collectionRequest);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.CancellationCodeSearchReturnValue GetBookingCancelledCategories(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest)
    {
        return base.Channel.GetBookingCancelledCategories(logonId, collectionRequest);
    }

    public IRIS.Law.WebServiceInterfaces.ReturnValue DeleteBooking(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Diary.DeleteData deleteData)
    {
        return base.Channel.DeleteBooking(logonId, deleteData);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.TaskSearchReturnValue MemberTaskSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Diary.TaskSearchCriteria criteria)
    {
        return base.Channel.MemberTaskSearch(logonId, collectionRequest, criteria);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.TaskSearchReturnValue MatterTaskSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Diary.TaskSearchCriteria criteria)
    {
        return base.Channel.MatterTaskSearch(logonId, collectionRequest, criteria);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.DiaryParameterReturnValue GetTaskTypes(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest)
    {
        return base.Channel.GetTaskTypes(logonId, collectionRequest);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.TaskReturnValue GetMemberTaskDetails(System.Guid logonId, int taskId)
    {
        return base.Channel.GetMemberTaskDetails(logonId, taskId);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.TaskReturnValue SaveTask(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Diary.Task taskDetails)
    {
        return base.Channel.SaveTask(logonId, taskDetails);
    }

    public IRIS.Law.WebServiceInterfaces.Diary.TaskReturnValue GetMatterTaskDetails(System.Guid logonId, System.Guid projectId, int taskId)
    {
        return base.Channel.GetMatterTaskDetails(logonId, projectId, taskId);
    }
}
