//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIS.Law.WebServiceInterfaces
{
    using System.Runtime.Serialization;



    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataListOfDocumentTypeSearchItemeLBmkNPm", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfDocumentTypeSearchItemeLBmkNPm : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int FirstRowNumberField;

        private IRIS.Law.WebServiceInterfaces.Document.DocumentTypeSearchItem[] RowsField;

        private int TotalRowCountField;


        private string _createdBy;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._createdBy;
            }
            set
            {
                this._createdBy = value;
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Document.DocumentTypeSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataListOfDocumentSearchItemeLBmkNPm", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfDocumentSearchItemeLBmkNPm : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int FirstRowNumberField;

        private IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem[] RowsField;

        private int TotalRowCountField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }

}
namespace IRIS.Law.WebServiceInterfaces.Document
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DownloadChunkReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DownloadChunkReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private byte[] BytesField;

        private int ChunkSizeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes
        {
            get
            {
                return this.BytesField;
            }
            set
            {
                this.BytesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChunkSize
        {
            get
            {
                return this.ChunkSizeField;
            }
            set
            {
                this.ChunkSizeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "StartDocumentUploadReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class StartDocumentUploadReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private int MaxChunkSizeField;

        private System.Guid TransferIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxChunkSize
        {
            get
            {
                return this.MaxChunkSizeField;
            }
            set
            {
                this.MaxChunkSizeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TransferId
        {
            get
            {
                return this.TransferIdField;
            }
            set
            {
                this.TransferIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DocumentReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem DocumentField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentTypeReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DocumentTypeReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.DataListOfDocumentTypeSearchItemeLBmkNPm DocumentTypeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfDocumentTypeSearchItemeLBmkNPm DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FileTypeReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class FileTypeReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.Document.FileTypeSearchItem[] FileTypeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Document.FileTypeSearchItem[] FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentSearchReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DocumentSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.DataListOfDocumentSearchItemeLBmkNPm DocumentField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfDocumentSearchItemeLBmkNPm Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentFolderListReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DocumentFolderListReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private string[] DocumentField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "StartDocumentDownloadReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class StartDocumentDownloadReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private string FileNameField;

        private byte[] HashField;

        private System.DateTime ModifiedDateField;

        private long SizeField;

        private System.Guid TransferIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Hash
        {
            get
            {
                return this.HashField;
            }
            set
            {
                this.HashField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TransferId
        {
            get
            {
                return this.TransferIdField;
            }
            set
            {
                this.TransferIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentSearchItem", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DocumentSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CreatedByField;
        
        private System.DateTime CreatedDateField;

        private System.Guid FeeEarnerIdField;

        private string FeeEarnerRefField;

        private string FileDescriptionField;

        private string FileNameField;

        private string FilePathField;

        private string FolderNameField;

        private int IdField;

        private string ImgfileNameField;

        private bool IsEncryptedField;

        private bool IsFolderField;

        private bool IsLockedField;
        
        private bool IsPublicField;

        private System.DateTime LastModifiedField;

        private System.DateTime ModifiedDateField;

        private string NotesField;

        private System.Guid ProjectIdField;

        private string ToolTipField;

        private string TypeField;

        private int TypeIdField;

        private bool UseVersioningField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FeeEarnerId
        {
            get
            {
                return this.FeeEarnerIdField;
            }
            set
            {
                this.FeeEarnerIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeEarnerRef
        {
            get
            {
                return this.FeeEarnerRefField;
            }
            set
            {
                this.FeeEarnerRefField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileDescription
        {
            get
            {
                return this.FileDescriptionField;
            }
            set
            {
                this.FileDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderName
        {
            get
            {
                return this.FolderNameField;
            }
            set
            {
                this.FolderNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgfileName
        {
            get
            {
                return this.ImgfileNameField;
            }
            set
            {
                this.ImgfileNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEncrypted
        {
            get
            {
                return this.IsEncryptedField;
            }
            set
            {
                this.IsEncryptedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFolder
        {
            get
            {
                return this.IsFolderField;
            }
            set
            {
                this.IsFolderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked
        {
            get
            {
                return this.IsLockedField;
            }
            set
            {
                this.IsLockedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublic
        {
            get
            {
                return this.IsPublicField;
            }
            set
            {
                this.IsPublicField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified
        {
            get
            {
                return this.LastModifiedField;
            }
            set
            {
                this.LastModifiedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolTip
        {
            get
            {
                return this.ToolTipField;
            }
            set
            {
                this.ToolTipField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId
        {
            get
            {
                return this.TypeIdField;
            }
            set
            {
                this.TypeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseVersioning
        {
            get
            {
                return this.UseVersioningField;
            }
            set
            {
                this.UseVersioningField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentTypeSearchItem", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DocumentTypeSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string DescriptionField;

        private int IdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FileTypeSearchItem", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class FileTypeSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string FileDescriptionField;

        private string FileExtensionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileDescription
        {
            get
            {
                return this.FileDescriptionField;
            }
            set
            {
                this.FileDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExtension
        {
            get
            {
                return this.FileExtensionField;
            }
            set
            {
                this.FileExtensionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentSearchCriteria", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DocumentSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {

        private int DocumentTypeField;

        private bool IsDeepSearchField;

        private bool IsMatchCaseField;

        private bool IsSubFolderSearchField;

        private string SearchStringField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeepSearch
        {
            get
            {
                return this.IsDeepSearchField;
            }
            set
            {
                this.IsDeepSearchField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMatchCase
        {
            get
            {
                return this.IsMatchCaseField;
            }
            set
            {
                this.IsMatchCaseField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSubFolderSearch
        {
            get
            {
                return this.IsSubFolderSearchField;
            }
            set
            {
                this.IsSubFolderSearchField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchString
        {
            get
            {
                return this.SearchStringField;
            }
            set
            {
                this.SearchStringField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DocumentTypeSearchCriteria", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Document")]
    public partial class DocumentTypeSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {

        private string DocTypeIDsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocTypeIDs
        {
            get
            {
                return this.DocTypeIDsField;
            }
            set
            {
                this.DocTypeIDsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.iris.co.uk/ILB/ClientService", ConfigurationName = "IDocumentService", SessionMode = System.ServiceModel.SessionMode.Required)]
public interface IDocumentService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/StartDocumentDownloadFor" +
        "Matter", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/StartDocumentDownloadFor" +
        "MatterResponse")]
    IRIS.Law.WebServiceInterfaces.Document.StartDocumentDownloadReturnValue StartDocumentDownloadForMatter(System.Guid logonId, System.Guid projectId, int DocumentId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/DocumentDownloadChunk", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/DocumentDownloadChunkRes" +
        "ponse")]
    IRIS.Law.WebServiceInterfaces.Document.DownloadChunkReturnValue DocumentDownloadChunk(System.Guid logonId, System.Guid TransferId, long FilePosition);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/DocumentDownloadComplete" +
        "", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/DocumentDownloadComplete" +
        "Response")]
    IRIS.Law.WebServiceInterfaces.ReturnValue DocumentDownloadComplete(System.Guid logonId, System.Guid TransferId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/StartNewDocumentUploadFo" +
        "rMatter", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/StartNewDocumentUploadFo" +
        "rMatterResponse")]
    IRIS.Law.WebServiceInterfaces.Document.StartDocumentUploadReturnValue StartNewDocumentUploadForMatter(System.Guid logonId, System.DateTime ModifiedDate, long Size, byte[] Hash, IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem docSearchItem);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/StartExistingDocumentUpl" +
        "oadForMatter", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/StartExistingDocumentUpl" +
        "oadForMatterResponse")]
    IRIS.Law.WebServiceInterfaces.Document.StartDocumentUploadReturnValue StartExistingDocumentUploadForMatter(System.Guid logonId, System.DateTime ModifiedDate, long Size, byte[] Hash, IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem docSearchItem);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/DocumentUploadChunk", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/DocumentUploadChunkRespo" +
        "nse")]
    IRIS.Law.WebServiceInterfaces.ReturnValue DocumentUploadChunk(System.Guid logonId, System.Guid TransferId, long FilePosition, int ChunkSize, byte[] Bytes);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/DocumentUploadComplete", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/DocumentUploadCompleteRe" +
        "sponse")]
    IRIS.Law.WebServiceInterfaces.Document.DocumentReturnValue DocumentUploadComplete(System.Guid logonId, System.Guid TransferId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/EditMatterDocumentDetail" +
        "s", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/EditMatterDocumentDetail" +
        "sResponse")]
    IRIS.Law.WebServiceInterfaces.Document.DocumentReturnValue EditMatterDocumentDetails(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem docSearchItem);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetDocumentDetails", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetDocumentDetailsRespon" +
        "se")]
    IRIS.Law.WebServiceInterfaces.Document.DocumentReturnValue GetDocumentDetails(System.Guid logonId, System.Guid projectId, int docId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetDocumentTypes", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetDocumentTypesResponse" +
        "")]
    IRIS.Law.WebServiceInterfaces.Document.DocumentTypeReturnValue GetDocumentTypes(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Document.DocumentTypeSearchCriteria criteria, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetFileTypes", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetFileTypesResponse")]
    IRIS.Law.WebServiceInterfaces.Document.FileTypeReturnValue GetFileTypes(System.Guid logonId);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetMatterDocumentForDeep" +
        "Search", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetMatterDocumentForDeep" +
        "SearchResponse")]
    IRIS.Law.WebServiceInterfaces.Document.DocumentSearchReturnValue GetMatterDocumentForDeepSearch(System.Guid logonId, System.Guid projectId, IRIS.Law.WebServiceInterfaces.Document.DocumentSearchCriteria criteria);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/MatterDocumentSearch", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/MatterDocumentSearchResp" +
        "onse")]
    IRIS.Law.WebServiceInterfaces.Document.DocumentSearchReturnValue MatterDocumentSearch(System.Guid logonId, System.Guid projectId, string OrderBy);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetDocumentFolderList", ReplyAction = "http://www.iris.co.uk/ILB/ClientService/IDocumentService/GetDocumentFolderListResp" +
        "onse")]
    IRIS.Law.WebServiceInterfaces.Document.DocumentFolderListReturnValue GetDocumentFolderList(System.Guid logonId, System.Guid projectId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDocumentServiceChannel : IDocumentService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DocumentServiceClient : System.ServiceModel.ClientBase<IDocumentService>, IDocumentService
{

    public DocumentServiceClient()
    {
    }

    public DocumentServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public DocumentServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public DocumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public DocumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public IRIS.Law.WebServiceInterfaces.Document.StartDocumentDownloadReturnValue StartDocumentDownloadForMatter(System.Guid logonId, System.Guid projectId, int DocumentId)
    {
        return base.Channel.StartDocumentDownloadForMatter(logonId, projectId, DocumentId);
    }

    public IRIS.Law.WebServiceInterfaces.Document.DownloadChunkReturnValue DocumentDownloadChunk(System.Guid logonId, System.Guid TransferId, long FilePosition)
    {
        return base.Channel.DocumentDownloadChunk(logonId, TransferId, FilePosition);
    }

    public IRIS.Law.WebServiceInterfaces.ReturnValue DocumentDownloadComplete(System.Guid logonId, System.Guid TransferId)
    {
        return base.Channel.DocumentDownloadComplete(logonId, TransferId);
    }

    public IRIS.Law.WebServiceInterfaces.Document.StartDocumentUploadReturnValue StartNewDocumentUploadForMatter(System.Guid logonId, System.DateTime ModifiedDate, long Size, byte[] Hash, IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem docSearchItem)
    {
        return base.Channel.StartNewDocumentUploadForMatter(logonId, ModifiedDate, Size, Hash, docSearchItem);
    }

    public IRIS.Law.WebServiceInterfaces.Document.StartDocumentUploadReturnValue StartExistingDocumentUploadForMatter(System.Guid logonId, System.DateTime ModifiedDate, long Size, byte[] Hash, IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem docSearchItem)
    {
        return base.Channel.StartExistingDocumentUploadForMatter(logonId, ModifiedDate, Size, Hash, docSearchItem);
    }

    public IRIS.Law.WebServiceInterfaces.ReturnValue DocumentUploadChunk(System.Guid logonId, System.Guid TransferId, long FilePosition, int ChunkSize, byte[] Bytes)
    {
        return base.Channel.DocumentUploadChunk(logonId, TransferId, FilePosition, ChunkSize, Bytes);
    }

    public IRIS.Law.WebServiceInterfaces.Document.DocumentReturnValue DocumentUploadComplete(System.Guid logonId, System.Guid TransferId)
    {
        return base.Channel.DocumentUploadComplete(logonId, TransferId);
    }

    public IRIS.Law.WebServiceInterfaces.Document.DocumentReturnValue EditMatterDocumentDetails(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Document.DocumentSearchItem docSearchItem)
    {
        return base.Channel.EditMatterDocumentDetails(logonId, docSearchItem);
    }

    public IRIS.Law.WebServiceInterfaces.Document.DocumentReturnValue GetDocumentDetails(System.Guid logonId, System.Guid projectId, int docId)
    {
        return base.Channel.GetDocumentDetails(logonId, projectId, docId);
    }

    public IRIS.Law.WebServiceInterfaces.Document.DocumentTypeReturnValue GetDocumentTypes(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Document.DocumentTypeSearchCriteria criteria, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest)
    {
        return base.Channel.GetDocumentTypes(logonId, criteria, collectionRequest);
    }

    public IRIS.Law.WebServiceInterfaces.Document.FileTypeReturnValue GetFileTypes(System.Guid logonId)
    {
        return base.Channel.GetFileTypes(logonId);
    }

    public IRIS.Law.WebServiceInterfaces.Document.DocumentSearchReturnValue GetMatterDocumentForDeepSearch(System.Guid logonId, System.Guid projectId, IRIS.Law.WebServiceInterfaces.Document.DocumentSearchCriteria criteria)
    {
        return base.Channel.GetMatterDocumentForDeepSearch(logonId, projectId, criteria);
    }

    public IRIS.Law.WebServiceInterfaces.Document.DocumentSearchReturnValue MatterDocumentSearch(System.Guid logonId, System.Guid projectId, string OrderBy)
    {
        return base.Channel.MatterDocumentSearch(logonId, projectId, OrderBy);
    }

    public IRIS.Law.WebServiceInterfaces.Document.DocumentFolderListReturnValue GetDocumentFolderList(System.Guid logonId, System.Guid projectId)
    {
        return base.Channel.GetDocumentFolderList(logonId, projectId);
    }
}
