//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIS.Law.WebServiceInterfaces
{
    using System.Runtime.Serialization;
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfChargeRateSearchItemN_SrA0M1O", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfChargeRateSearchItemN_SrA0M1O : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Time.ChargeRateSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.ChargeRateSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfCourtTypeSearchItemN_SrA0M1O", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfCourtTypeSearchItemN_SrA0M1O : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Time.CourtTypeSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.CourtTypeSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfUnPostedTimeSearchItemN_SrA0M1O", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfUnPostedTimeSearchItemN_SrA0M1O : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Time.UnPostedTimeSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.UnPostedTimeSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfTimeTypeSearchItemN_SrA0M1O", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfTimeTypeSearchItemN_SrA0M1O : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Time.TimeTypeSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.TimeTypeSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfAdvocacyTypeSearchItemN_SrA0M1O", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfAdvocacyTypeSearchItemN_SrA0M1O : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Time.AdvocacyTypeSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.AdvocacyTypeSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfAttendanceIndividualSearchItemN_SrA0M1O", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfAttendanceIndividualSearchItemN_SrA0M1O : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Time.AttendanceIndividualSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.AttendanceIndividualSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfServiceSearchItemN_SrA0M1O", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfServiceSearchItemN_SrA0M1O : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Time.ServiceSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.ServiceSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListOfServiceContactSearchItemN_SrA0M1O", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfServiceContactSearchItemN_SrA0M1O : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstRowNumberField;
        
        private IRIS.Law.WebServiceInterfaces.Time.ServiceContactSearchItem[] RowsField;
        
        private int TotalRowCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.ServiceContactSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }
}
namespace IRIS.Law.WebServiceInterfaces.Time
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourtTypeReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class CourtTypeReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfCourtTypeSearchItemN_SrA0M1O CourtTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfCourtTypeSearchItemN_SrA0M1O CourtTypes
        {
            get
            {
                return this.CourtTypesField;
            }
            set
            {
                this.CourtTypesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnPostedTimeSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class UnPostedTimeSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfUnPostedTimeSearchItemN_SrA0M1O UnPostedTimeSheetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfUnPostedTimeSearchItemN_SrA0M1O UnPostedTimeSheet
        {
            get
            {
                return this.UnPostedTimeSheetField;
            }
            set
            {
                this.UnPostedTimeSheetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeTypeSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class TimeTypeSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfTimeTypeSearchItemN_SrA0M1O TimeTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfTimeTypeSearchItemN_SrA0M1O TimeTypes
        {
            get
            {
                return this.TimeTypesField;
            }
            set
            {
                this.TimeTypesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class TimeReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.Time.TimeAdditionalDetail AdditionalDetailField;
        
        private IRIS.Law.WebServiceInterfaces.Time.Time TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.TimeAdditionalDetail AdditionalDetail
        {
            get
            {
                return this.AdditionalDetailField;
            }
            set
            {
                this.AdditionalDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Time.Time Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodDetailsReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class PeriodDetailsReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private string ErrorMessageField;

        private int PeriodIdField;

        private bool IsValidFinancialPostingPeriodField;

        private int PeriodStatusField;
        
        private string PostingPeriodNumberField;
        
        private string WarningMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodId
        {
            get
            {
                return this.PeriodIdField;
            }
            set
            {
                this.PeriodIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValidFinancialPostingPeriod
        {
            get
            {
                return this.IsValidFinancialPostingPeriodField;
            }
            set
            {
                this.IsValidFinancialPostingPeriodField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodStatus
        {
            get
            {
                return this.PeriodStatusField;
            }
            set
            {
                this.PeriodStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostingPeriodNumber
        {
            get
            {
                return this.PostingPeriodNumberField;
            }
            set
            {
                this.PostingPeriodNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningMessage
        {
            get
            {
                return this.WarningMessageField;
            }
            set
            {
                this.WarningMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvocacyTypeSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class AdvocacyTypeSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfAdvocacyTypeSearchItemN_SrA0M1O AdvocacyTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfAdvocacyTypeSearchItemN_SrA0M1O AdvocacyType
        {
            get
            {
                return this.AdvocacyTypeField;
            }
            set
            {
                this.AdvocacyTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttendanceIndividualSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class AttendanceIndividualSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfAttendanceIndividualSearchItemN_SrA0M1O AttendanceIndividualField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfAttendanceIndividualSearchItemN_SrA0M1O AttendanceIndividual
        {
            get
            {
                return this.AttendanceIndividualField;
            }
            set
            {
                this.AttendanceIndividualField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class ServiceSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfServiceSearchItemN_SrA0M1O ServiceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfServiceSearchItemN_SrA0M1O Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceContactSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class ServiceContactSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfServiceContactSearchItemN_SrA0M1O ServiceContactField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfServiceContactSearchItemN_SrA0M1O ServiceContact
        {
            get
            {
                return this.ServiceContactField;
            }
            set
            {
                this.ServiceContactField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChargeRateSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class ChargeRateSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfChargeRateSearchItemN_SrA0M1O ChargeRatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfChargeRateSearchItemN_SrA0M1O ChargeRates
        {
            get
            {
                return this.ChargeRatesField;
            }
            set
            {
                this.ChargeRatesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourtTypeSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class CourtTypeSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnPostedTimeSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class UnPostedTimeSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BillingTypeActiveField;
        
        private bool BillingTypeArchivedField;
        
        private int CurrencyIdField;
        
        private int DepartmentIdField;
        
        private string MatterDescriptionField;
        
        private string MatterReferenceField;
        
        private System.Guid MemberIdField;
        
        private System.Guid OrganisationIdField;
        
        private System.Guid ProjectIdField;
        
        private string TimeField;
        
        private decimal TimeChargeField;
        
        private string TimeCommentsField;
        
        private decimal TimeCostField;
        
        private System.DateTime TimeDateField;
        
        private int TimeElapsedField;
        
        private int TimeIdField;
        
        private bool TimeLAAskedField;
        
        private string TimeTypeCodeField;
        
        private string TimeTypeDescriptionField;
        
        private System.Guid TimeTypeIdField;
        
        private string UnitsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BillingTypeActive
        {
            get
            {
                return this.BillingTypeActiveField;
            }
            set
            {
                this.BillingTypeActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BillingTypeArchived
        {
            get
            {
                return this.BillingTypeArchivedField;
            }
            set
            {
                this.BillingTypeArchivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyId
        {
            get
            {
                return this.CurrencyIdField;
            }
            set
            {
                this.CurrencyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId
        {
            get
            {
                return this.DepartmentIdField;
            }
            set
            {
                this.DepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatterDescription
        {
            get
            {
                return this.MatterDescriptionField;
            }
            set
            {
                this.MatterDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatterReference
        {
            get
            {
                return this.MatterReferenceField;
            }
            set
            {
                this.MatterReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MemberId
        {
            get
            {
                return this.MemberIdField;
            }
            set
            {
                this.MemberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganisationId
        {
            get
            {
                return this.OrganisationIdField;
            }
            set
            {
                this.OrganisationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimeCharge
        {
            get
            {
                return this.TimeChargeField;
            }
            set
            {
                this.TimeChargeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeComments
        {
            get
            {
                return this.TimeCommentsField;
            }
            set
            {
                this.TimeCommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TimeCost
        {
            get
            {
                return this.TimeCostField;
            }
            set
            {
                this.TimeCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeDate
        {
            get
            {
                return this.TimeDateField;
            }
            set
            {
                this.TimeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeElapsed
        {
            get
            {
                return this.TimeElapsedField;
            }
            set
            {
                this.TimeElapsedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeId
        {
            get
            {
                return this.TimeIdField;
            }
            set
            {
                this.TimeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TimeLAAsked
        {
            get
            {
                return this.TimeLAAskedField;
            }
            set
            {
                this.TimeLAAskedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeTypeCode
        {
            get
            {
                return this.TimeTypeCodeField;
            }
            set
            {
                this.TimeTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeTypeDescription
        {
            get
            {
                return this.TimeTypeDescriptionField;
            }
            set
            {
                this.TimeTypeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TimeTypeId
        {
            get
            {
                return this.TimeTypeIdField;
            }
            set
            {
                this.TimeTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Units
        {
            get
            {
                return this.UnitsField;
            }
            set
            {
                this.UnitsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeTypeSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class TimeTypeSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CatIdField;
        
        private string DescriptionField;

        private string CodeField;
        
        private System.Guid IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CatId
        {
            get
            {
                return this.CatIdField;
            }
            set
            {
                this.CatIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeAdditionalDetail", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class TimeAdditionalDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private IRIS.Law.Services.Pms.Time.DetailLocation AdditionalDetailsLocationField;
        
        private int[] AdvocacyTypesField;
        
        private int[] AttendanceIndividualsField;
        
        private IRIS.Law.Services.Pms.Time.AdditionalDetails CurrentAdditionalDetailsField;
        
        private decimal FaresAmountField;
        
        private string FaresDescriptionField;
        
        private System.Guid FileReviewsProjectIdField;
        
        private bool IsFaceToFaceField;
        
        private bool IsLAHearingAdjournedField;
        
        private bool IsLASubstantiveHearingAttendField;
        
        private bool IsLAYouthField;
        
        private bool IsTravelWaitingDetCentreField;
        
        private System.Guid LAIdField;
        
        private bool LAIsJRFormFillingField;
        
        private int LASuspectField;
        
        private int MilesField;
        
        private int RunningHoursField;
        
        private int RunningMinutesField;
        
        private int TimeIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.Services.Pms.Time.DetailLocation AdditionalDetailsLocation
        {
            get
            {
                return this.AdditionalDetailsLocationField;
            }
            set
            {
                this.AdditionalDetailsLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] AdvocacyTypes
        {
            get
            {
                return this.AdvocacyTypesField;
            }
            set
            {
                this.AdvocacyTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] AttendanceIndividuals
        {
            get
            {
                return this.AttendanceIndividualsField;
            }
            set
            {
                this.AttendanceIndividualsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.Services.Pms.Time.AdditionalDetails CurrentAdditionalDetails
        {
            get
            {
                return this.CurrentAdditionalDetailsField;
            }
            set
            {
                this.CurrentAdditionalDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FaresAmount
        {
            get
            {
                return this.FaresAmountField;
            }
            set
            {
                this.FaresAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaresDescription
        {
            get
            {
                return this.FaresDescriptionField;
            }
            set
            {
                this.FaresDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FileReviewsProjectId
        {
            get
            {
                return this.FileReviewsProjectIdField;
            }
            set
            {
                this.FileReviewsProjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFaceToFace
        {
            get
            {
                return this.IsFaceToFaceField;
            }
            set
            {
                this.IsFaceToFaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLAHearingAdjourned
        {
            get
            {
                return this.IsLAHearingAdjournedField;
            }
            set
            {
                this.IsLAHearingAdjournedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLASubstantiveHearingAttend
        {
            get
            {
                return this.IsLASubstantiveHearingAttendField;
            }
            set
            {
                this.IsLASubstantiveHearingAttendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLAYouth
        {
            get
            {
                return this.IsLAYouthField;
            }
            set
            {
                this.IsLAYouthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTravelWaitingDetCentre
        {
            get
            {
                return this.IsTravelWaitingDetCentreField;
            }
            set
            {
                this.IsTravelWaitingDetCentreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LAId
        {
            get
            {
                return this.LAIdField;
            }
            set
            {
                this.LAIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LAIsJRFormFilling
        {
            get
            {
                return this.LAIsJRFormFillingField;
            }
            set
            {
                this.LAIsJRFormFillingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LASuspect
        {
            get
            {
                return this.LASuspectField;
            }
            set
            {
                this.LASuspectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Miles
        {
            get
            {
                return this.MilesField;
            }
            set
            {
                this.MilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RunningHours
        {
            get
            {
                return this.RunningHoursField;
            }
            set
            {
                this.RunningHoursField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RunningMinutes
        {
            get
            {
                return this.RunningMinutesField;
            }
            set
            {
                this.RunningMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeId
        {
            get
            {
                return this.TimeIdField;
            }
            set
            {
                this.TimeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Time", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class Time : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private bool DontCheckLimitsField;

        private int BillingCodeIDField;
        
        private System.Guid FeeEarnerIdField;
        
        private int IdField;
        
        private string NotesField;
        
        private System.Guid ProjectIdField;
        
        private System.Guid TimeTypeIdField;
        
        private int UnitsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DontCheckLimits
        {
            get
            {
                return this.DontCheckLimitsField;
            }
            set
            {
                this.DontCheckLimitsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillingCodeID
        {
            get
            {
                return this.BillingCodeIDField;
            }
            set
            {
                this.BillingCodeIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FeeEarnerId
        {
            get
            {
                return this.FeeEarnerIdField;
            }
            set
            {
                this.FeeEarnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TimeTypeId
        {
            get
            {
                return this.TimeTypeIdField;
            }
            set
            {
                this.TimeTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Units
        {
            get
            {
                return this.UnitsField;
            }
            set
            {
                this.UnitsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvocacyTypeSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class AdvocacyTypeSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string DesciptionField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desciption
        {
            get
            {
                return this.DesciptionField;
            }
            set
            {
                this.DesciptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttendanceIndividualSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class AttendanceIndividualSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string DesciptionField;
        
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desciption
        {
            get
            {
                return this.DesciptionField;
            }
            set
            {
                this.DesciptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class ServiceSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressHouseNameField;
        
        private string AddressLine1Field;
        
        private string AddressPostcodeField;
        
        private string AddressStreetNoField;
        
        private string AddressTownField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressHouseName
        {
            get
            {
                return this.AddressHouseNameField;
            }
            set
            {
                this.AddressHouseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressPostcode
        {
            get
            {
                return this.AddressPostcodeField;
            }
            set
            {
                this.AddressPostcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressStreetNo
        {
            get
            {
                return this.AddressStreetNoField;
            }
            set
            {
                this.AddressStreetNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressTown
        {
            get
            {
                return this.AddressTownField;
            }
            set
            {
                this.AddressTownField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceContactSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class ServiceContactSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid MemberIdField;
        
        private string PersonNameField;
        
        private string PersonSurnameField;
        
        private string PersonTitleField;
        
        private string PositionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MemberId
        {
            get
            {
                return this.MemberIdField;
            }
            set
            {
                this.MemberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonName
        {
            get
            {
                return this.PersonNameField;
            }
            set
            {
                this.PersonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonSurname
        {
            get
            {
                return this.PersonSurnameField;
            }
            set
            {
                this.PersonSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonTitle
        {
            get
            {
                return this.PersonTitleField;
            }
            set
            {
                this.PersonTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChargeRateSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class ChargeRateSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CourtIdField;
        
        private string DescriptionField;
        
        private string DescriptionCourtField;
        
        private System.Guid DescriptionIdField;
        
        private string DescriptionReferenceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourtId
        {
            get
            {
                return this.CourtIdField;
            }
            set
            {
                this.CourtIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionCourt
        {
            get
            {
                return this.DescriptionCourtField;
            }
            set
            {
                this.DescriptionCourtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DescriptionId
        {
            get
            {
                return this.DescriptionIdField;
            }
            set
            {
                this.DescriptionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionReference
        {
            get
            {
                return this.DescriptionReferenceField;
            }
            set
            {
                this.DescriptionReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChargeRateSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class ChargeRateSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {
        
        private bool IsArchivedField;
        
        private bool IsPublicFundedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArchived
        {
            get
            {
                return this.IsArchivedField;
            }
            set
            {
                this.IsArchivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublicFunded
        {
            get
            {
                return this.IsPublicFundedField;
            }
            set
            {
                this.IsPublicFundedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnPostedTimeSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class UnPostedTimeSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {
        
        private string FeeEarnerRefField;
        
        private System.DateTime TimeDateField;
        
        private int UserIdField;

        private string OrderByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeEarnerRef
        {
            get
            {
                return this.FeeEarnerRefField;
            }
            set
            {
                this.FeeEarnerRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeDate
        {
            get
            {
                return this.TimeDateField;
            }
            set
            {
                this.TimeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }

        
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeTypeSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class TimeTypeSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {
        
        private bool IncludeArchivedField;
        
        private System.Guid ProjectIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeArchived
        {
            get
            {
                return this.IncludeArchivedField;
            }
            set
            {
                this.IncludeArchivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class ServiceSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {
        
        private int IndustryIdField;
        
        private bool LSCIDOnlyField;

        private string OrderByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndustryId
        {
            get
            {
                return this.IndustryIdField;
            }
            set
            {
                this.IndustryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LSCIDOnly
        {
            get
            {
                return this.LSCIDOnlyField;
            }
            set
            {
                this.LSCIDOnlyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderBy
        {
            get
            {
                return this.OrderByField;
            }
            set
            {
                this.OrderByField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourtTypeSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class CourtTypeSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {
        
        private string DescriptionField;
        
        private bool IncludeArchivedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeArchived
        {
            get
            {
                return this.IncludeArchivedField;
            }
            set
            {
                this.IncludeArchivedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class PeriodCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private bool IsAllowedPostBack2ClosedYearField;
        
        private bool IsPostingVATableField;
        
        private bool IsTimeField;
        
        private System.Guid ProjectIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllowedPostBack2ClosedYear
        {
            get
            {
                return this.IsAllowedPostBack2ClosedYearField;
            }
            set
            {
                this.IsAllowedPostBack2ClosedYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPostingVATable
        {
            get
            {
                return this.IsPostingVATableField;
            }
            set
            {
                this.IsPostingVATableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTime
        {
            get
            {
                return this.IsTimeField;
            }
            set
            {
                this.IsTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TimeTypeCriteria", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class TimeTypeCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid ProjectIdField;

        private System.Guid TimeTypeIdField;

        private System.Guid FeeEarnerIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TimeTypeId
        {
            get
            {
                return this.TimeTypeIdField;
            }
            set
            {
                this.TimeTypeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FeeEarnerId
        {
            get
            {
                return this.FeeEarnerIdField;
            }
            set
            {
                this.FeeEarnerIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSheet", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Time")]
    public partial class TimeSheet : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CurrencyIdField;
        
        private int DepartmentIdField;
        
        private decimal MasterPostedChargeField;
        
        private decimal MasterPostedCostField;
        
        private string MemberIdField;
        
        private System.Guid OrganisationIdField;
        
        private int PeriodIdField;
        
        private int PeriodMinutesField;
        
        private System.Guid ProjectIdField;
        
        private int TimeIdField;
        
        private System.Guid TimeTypeIdField;
        
        private decimal WorkingPostedChargeField;
        
        private decimal WorkingPostedCostField;

        private System.DateTime TimeDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyId
        {
            get
            {
                return this.CurrencyIdField;
            }
            set
            {
                this.CurrencyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId
        {
            get
            {
                return this.DepartmentIdField;
            }
            set
            {
                this.DepartmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MasterPostedCharge
        {
            get
            {
                return this.MasterPostedChargeField;
            }
            set
            {
                this.MasterPostedChargeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MasterPostedCost
        {
            get
            {
                return this.MasterPostedCostField;
            }
            set
            {
                this.MasterPostedCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberId
        {
            get
            {
                return this.MemberIdField;
            }
            set
            {
                this.MemberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganisationId
        {
            get
            {
                return this.OrganisationIdField;
            }
            set
            {
                this.OrganisationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodId
        {
            get
            {
                return this.PeriodIdField;
            }
            set
            {
                this.PeriodIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodMinutes
        {
            get
            {
                return this.PeriodMinutesField;
            }
            set
            {
                this.PeriodMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProjectId
        {
            get
            {
                return this.ProjectIdField;
            }
            set
            {
                this.ProjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeId
        {
            get
            {
                return this.TimeIdField;
            }
            set
            {
                this.TimeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TimeTypeId
        {
            get
            {
                return this.TimeTypeIdField;
            }
            set
            {
                this.TimeTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WorkingPostedCharge
        {
            get
            {
                return this.WorkingPostedChargeField;
            }
            set
            {
                this.WorkingPostedChargeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WorkingPostedCost
        {
            get
            {
                return this.WorkingPostedCostField;
            }
            set
            {
                this.WorkingPostedCostField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeDate
        {
            get
            {
                return this.TimeDateField;
            }
            set
            {
                this.TimeDateField = value;
            }
        }
    }
}
namespace IRIS.Law.Services.Pms.Time
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailLocation", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.Services.Pms.Time")]
    public enum DetailLocation : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotApplicable = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Court = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PoliceStation = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalDetails", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.Services.Pms.Time")]
    public enum AdditionalDetails : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Advocacy = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attendance = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CivilImmigrationAsylumJRFormFilling = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CivilImmigrationAsylumMentalHearing = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CivilImmigrationAsylumSubstantiveHearing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CivilImmigrationAsylumTravelWaiting = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CourtDutyAttendance = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileReviews = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PoliceStationCalls = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PoliceStationAttendance = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RunningTime = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Travel = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 12,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iris.co.uk/ILB/TimeService", ConfigurationName="ITimeService", SessionMode=System.ServiceModel.SessionMode.Required)]
public interface ITimeService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/ChargeRateSearch", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/ChargeRateSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Time.ChargeRateSearchReturnValue ChargeRateSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/CourtTypeSearch", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/CourtTypeSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Time.CourtTypeReturnValue CourtTypeSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.CourtTypeSearchCriteria criteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/ChargeRateOnPublicFundingSearc" +
        "h", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/ChargeRateOnPublicFundingSearc" +
        "hResponse")]
    IRIS.Law.WebServiceInterfaces.Time.ChargeRateSearchReturnValue ChargeRateOnPublicFundingSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.ChargeRateSearchCriteria criteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/UnPostedTimeSheetSearch", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/UnPostedTimeSheetSearchRespons" +
        "e")]
    IRIS.Law.WebServiceInterfaces.Time.UnPostedTimeSearchReturnValue UnPostedTimeSheetSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.UnPostedTimeSearchCriteria criteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/TimeTypeSearch", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/TimeTypeSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Time.TimeTypeSearchReturnValue TimeTypeSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.TimeTypeSearchCriteria criteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/GetTime", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/GetTimeResponse")]
    IRIS.Law.WebServiceInterfaces.Time.TimeReturnValue GetTime(System.Guid logonId, int timeId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/AddTime", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/AddTimeResponse")]
    IRIS.Law.WebServiceInterfaces.Time.TimeReturnValue AddTime(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.Time time, IRIS.Law.WebServiceInterfaces.Time.TimeAdditionalDetail additionalTime, bool postToAccounts);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/ValidatePeriod", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/ValidatePeriodResponse")]
    IRIS.Law.WebServiceInterfaces.Time.PeriodDetailsReturnValue ValidatePeriod(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.PeriodCriteria criteria);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/TimeService/ITimeService/ValidateTimeTypeForPosting", ReplyAction = "http://www.iris.co.uk/ILB/TimeService/ITimeService/ValidateTimeTypeForPostingResponse")]
    IRIS.Law.WebServiceInterfaces.ReturnValue ValidateTimeTypeForPosting(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.TimeTypeCriteria criteria);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.iris.co.uk/ILB/TimeService/ITimeService/UpdateTime", ReplyAction = "http://www.iris.co.uk/ILB/TimeService/ITimeService/UpdateTimeResponse")]
    IRIS.Law.WebServiceInterfaces.Time.TimeReturnValue UpdateTime(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.Time time, IRIS.Law.WebServiceInterfaces.Time.TimeAdditionalDetail additionalTime);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/PostTime", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/PostTimeResponse")]
    IRIS.Law.WebServiceInterfaces.ReturnValue PostTime(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.TimeSheet timeSheet);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/AdvocacyTypeSearch", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/AdvocacyTypeSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Time.AdvocacyTypeSearchReturnValue AdvocacyTypeSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/AttendanceIndividualSearch", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/AttendanceIndividualSearchResp" +
        "onse")]
    IRIS.Law.WebServiceInterfaces.Time.AttendanceIndividualSearchReturnValue AttendanceIndividualSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/GetAddtionalDetailTime", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/GetAddtionalDetailTimeResponse" +
        "")]
    IRIS.Law.WebServiceInterfaces.Time.TimeReturnValue GetAddtionalDetailTime(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.Time tim);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/ServiceSearch", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/ServiceSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Time.ServiceSearchReturnValue ServiceSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, int associationRoleId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/ServiceSearchOnIndustry", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/ServiceSearchOnIndustryRespons" +
        "e")]
    IRIS.Law.WebServiceInterfaces.Time.ServiceSearchReturnValue ServiceSearchOnIndustry(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.ServiceSearchCriteria criteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/TimeService/ITimeService/ServiceContactSearch", ReplyAction="http://www.iris.co.uk/ILB/TimeService/ITimeService/ServiceContactSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Time.ServiceContactSearchReturnValue ServiceContactSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, System.Guid assocParentOrgID, string OrderBy);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITimeServiceChannel : ITimeService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class TimeServiceClient : System.ServiceModel.ClientBase<ITimeService>, ITimeService
{
    
    public TimeServiceClient()
    {
    }
    
    public TimeServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TimeServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TimeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TimeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.ChargeRateSearchReturnValue ChargeRateSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest)
    {
        return base.Channel.ChargeRateSearch(logonId, collectionRequest);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.CourtTypeReturnValue CourtTypeSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.CourtTypeSearchCriteria criteria)
    {
        return base.Channel.CourtTypeSearch(logonId, collectionRequest, criteria);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.ChargeRateSearchReturnValue ChargeRateOnPublicFundingSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.ChargeRateSearchCriteria criteria)
    {
        return base.Channel.ChargeRateOnPublicFundingSearch(logonId, collectionRequest, criteria);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.UnPostedTimeSearchReturnValue UnPostedTimeSheetSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.UnPostedTimeSearchCriteria criteria)
    {
        return base.Channel.UnPostedTimeSheetSearch(logonId, collectionRequest, criteria);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.TimeTypeSearchReturnValue TimeTypeSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.TimeTypeSearchCriteria criteria)
    {
        return base.Channel.TimeTypeSearch(logonId, collectionRequest, criteria);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.TimeReturnValue GetTime(System.Guid logonId, int timeId)
    {
        return base.Channel.GetTime(logonId, timeId);
    }

    public IRIS.Law.WebServiceInterfaces.Time.TimeReturnValue AddTime(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.Time time, IRIS.Law.WebServiceInterfaces.Time.TimeAdditionalDetail additionalTime, bool postToAccounts)
    {
        return base.Channel.AddTime(logonId, time, additionalTime, postToAccounts);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.PeriodDetailsReturnValue ValidatePeriod(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.PeriodCriteria criteria)
    {
        return base.Channel.ValidatePeriod(logonId, criteria);
    }

    public IRIS.Law.WebServiceInterfaces.ReturnValue ValidateTimeTypeForPosting(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.TimeTypeCriteria criteria)
    {
        return base.Channel.ValidateTimeTypeForPosting(logonId, criteria);
    }

    public IRIS.Law.WebServiceInterfaces.Time.TimeReturnValue UpdateTime(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.Time time, IRIS.Law.WebServiceInterfaces.Time.TimeAdditionalDetail additionalTime)
    {
        return base.Channel.UpdateTime(logonId, time, additionalTime);
    }
    
    public IRIS.Law.WebServiceInterfaces.ReturnValue PostTime(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.TimeSheet timeSheet)
    {
        return base.Channel.PostTime(logonId, timeSheet);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.AdvocacyTypeSearchReturnValue AdvocacyTypeSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest)
    {
        return base.Channel.AdvocacyTypeSearch(logonId, collectionRequest);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.AttendanceIndividualSearchReturnValue AttendanceIndividualSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest)
    {
        return base.Channel.AttendanceIndividualSearch(logonId, collectionRequest);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.TimeReturnValue GetAddtionalDetailTime(System.Guid logonId, IRIS.Law.WebServiceInterfaces.Time.Time tim)
    {
        return base.Channel.GetAddtionalDetailTime(logonId, tim);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.ServiceSearchReturnValue ServiceSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, int associationRoleId)
    {
        return base.Channel.ServiceSearch(logonId, collectionRequest, associationRoleId);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.ServiceSearchReturnValue ServiceSearchOnIndustry(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Time.ServiceSearchCriteria criteria)
    {
        return base.Channel.ServiceSearchOnIndustry(logonId, collectionRequest, criteria);
    }
    
    public IRIS.Law.WebServiceInterfaces.Time.ServiceContactSearchReturnValue ServiceContactSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, System.Guid assocParentOrgID, string OrderBy)
    {
        return base.Channel.ServiceContactSearch(logonId, collectionRequest, assocParentOrgID, OrderBy);
    }
}
