//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRIS.Law.WebServiceInterfaces
{
    //using System.Runtime.Serialization;
    
    
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Name="CollectionRequest", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    //public partial class CollectionRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    //{
        
    //    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
    //    private bool ForceRefreshField;
        
    //    private int RowCountField;
        
    //    private int StartRowField;
        
    //    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    //    {
    //        get
    //        {
    //            return this.extensionDataField;
    //        }
    //        set
    //        {
    //            this.extensionDataField = value;
    //        }
    //    }
        
    //    [System.Runtime.Serialization.DataMemberAttribute()]
    //    public bool ForceRefresh
    //    {
    //        get
    //        {
    //            return this.ForceRefreshField;
    //        }
    //        set
    //        {
    //            this.ForceRefreshField = value;
    //        }
    //    }
        
    //    [System.Runtime.Serialization.DataMemberAttribute()]
    //    public int RowCount
    //    {
    //        get
    //        {
    //            return this.RowCountField;
    //        }
    //        set
    //        {
    //            this.RowCountField = value;
    //        }
    //    }
        
    //    [System.Runtime.Serialization.DataMemberAttribute()]
    //    public int StartRow
    //    {
    //        get
    //        {
    //            return this.StartRowField;
    //        }
    //        set
    //        {
    //            this.StartRowField = value;
    //        }
    //    }
    //}
    
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Name="SearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    //[System.Runtime.Serialization.KnownTypeAttribute(typeof(IRIS.Law.WebServiceInterfaces.Utilities.UserSearchCriteria))]
    //public partial class SearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    //{
        
    //    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
    //    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    //    {
    //        get
    //        {
    //            return this.extensionDataField;
    //        }
    //        set
    //        {
    //            this.extensionDataField = value;
    //        }
    //    }
    //}
    
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Name="ReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    //[System.Runtime.Serialization.KnownTypeAttribute(typeof(IRIS.Law.WebServiceInterfaces.Utilities.UserSearchReturnValue))]
    //public partial class ReturnValue : object, System.Runtime.Serialization.IExtensibleDataObject
    //{
        
    //    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
    //    private string MessageField;
        
    //    private bool SuccessField;
        
    //    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    //    {
    //        get
    //        {
    //            return this.extensionDataField;
    //        }
    //        set
    //        {
    //            this.extensionDataField = value;
    //        }
    //    }
        
    //    [System.Runtime.Serialization.DataMemberAttribute()]
    //    public string Message
    //    {
    //        get
    //        {
    //            return this.MessageField;
    //        }
    //        set
    //        {
    //            this.MessageField = value;
    //        }
    //    }
        
    //    [System.Runtime.Serialization.DataMemberAttribute()]
    //    public bool Success
    //    {
    //        get
    //        {
    //            return this.SuccessField;
    //        }
    //        set
    //        {
    //            this.SuccessField = value;
    //        }
    //    }
    //}

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DataListOfUserSearchItemloMuHEwj", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces")]
    public partial class DataListOfUserSearchItemloMuHEwj : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int FirstRowNumberField;

        private IRIS.Law.WebServiceInterfaces.Utilities.UserSearchItem[] RowsField;

        private int TotalRowCountField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstRowNumber
        {
            get
            {
                return this.FirstRowNumberField;
            }
            set
            {
                this.FirstRowNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Utilities.UserSearchItem[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRowCount
        {
            get
            {
                return this.TotalRowCountField;
            }
            set
            {
                this.TotalRowCountField = value;
            }
        }
    }


}


namespace IRIS.Law.WebServiceInterfaces.Utilities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Utilities")]
    public partial class UserSearchCriteria : IRIS.Law.WebServiceInterfaces.SearchCriteria
    {
        
        private int? UserTypeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int? UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
    

        private string NameField;    
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UserReturnValue", Namespace = "http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Utilities")]
    public partial class UserReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {

        private IRIS.Law.WebServiceInterfaces.Utilities.User UserField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Utilities.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkTypeReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Utilities")]
    public partial class WorkTypeReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.Utilities.WorkType WorkTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.Utilities.WorkType WorkType
        {
            get
            {
                return this.WorkTypeField;
            }
            set
            {
                this.WorkTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBVersionReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Utilities")]
    public partial class DBVersionReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private string DBVersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBVersion
        {
            get
            {
                return this.DBVersionField;
            }
            set
            {
                this.DBVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSearchReturnValue", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Utilities")]
    public partial class UserSearchReturnValue : IRIS.Law.WebServiceInterfaces.ReturnValue
    {
        
        private IRIS.Law.WebServiceInterfaces.DataListOfUserSearchItemloMuHEwj UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IRIS.Law.WebServiceInterfaces.DataListOfUserSearchItemloMuHEwj Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Utilities")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ForenameField;
        
        private string LastnameField;
        
        private System.Guid MemOrOrgIdField;
        
        private string NameField;
        
        private string TitleField;
        
        private int UidField;
        
        private System.Guid UserDefaBranchField;
        
        private int UserDefaDepartmentField;
        
        private System.Guid UserDefaEarnerField;
        
        private System.Guid UserDefaPartnerField;
        
        private System.Guid UserDefaWorkTypeField;
        
        private int UserTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Forename
        {
            get
            {
                return this.ForenameField;
            }
            set
            {
                this.ForenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname
        {
            get
            {
                return this.LastnameField;
            }
            set
            {
                this.LastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MemOrOrgId
        {
            get
            {
                return this.MemOrOrgIdField;
            }
            set
            {
                this.MemOrOrgIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Uid
        {
            get
            {
                return this.UidField;
            }
            set
            {
                this.UidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserDefaBranch
        {
            get
            {
                return this.UserDefaBranchField;
            }
            set
            {
                this.UserDefaBranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserDefaDepartment
        {
            get
            {
                return this.UserDefaDepartmentField;
            }
            set
            {
                this.UserDefaDepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserDefaEarner
        {
            get
            {
                return this.UserDefaEarnerField;
            }
            set
            {
                this.UserDefaEarnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserDefaPartner
        {
            get
            {
                return this.UserDefaPartnerField;
            }
            set
            {
                this.UserDefaPartnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserDefaWorkType
        {
            get
            {
                return this.UserDefaWorkTypeField;
            }
            set
            {
                this.UserDefaWorkTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkType", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Utilities")]
    public partial class WorkType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ApplicationIDField;
        
        private int BillingCodeCategoryIDField;
        
        private System.Guid CLHeaderIDField;
        
        private System.Guid ChargeDescIDField;
        
        private string DeptNoField;
        
        private string ExtInfoTypeDefaultCatNameField;
        
        private int ExtendedInfoTypeDefaultCatIDField;
        
        private int NominalIDField;
        
        private int WorkCatIDField;
        
        private string WorkTypeArchivedField;
        
        private string WorkTypeCodeField;
        
        private int WorkTypeDeptField;
        
        private string WorkTypeDescriptionField;
        
        private string WorkTypeDisbLimitField;
        
        private System.Guid WorkTypeIDField;
        
        private string WorkTypeIsLAField;
        
        private string WorkTypeOverallLimitField;
        
        private string WorkTypeQuoteField;
        
        private string WorkTypeTimeLimitField;
        
        private string WorkTypeWipLimitField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationID
        {
            get
            {
                return this.ApplicationIDField;
            }
            set
            {
                this.ApplicationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillingCodeCategoryID
        {
            get
            {
                return this.BillingCodeCategoryIDField;
            }
            set
            {
                this.BillingCodeCategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CLHeaderID
        {
            get
            {
                return this.CLHeaderIDField;
            }
            set
            {
                this.CLHeaderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ChargeDescID
        {
            get
            {
                return this.ChargeDescIDField;
            }
            set
            {
                this.ChargeDescIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptNo
        {
            get
            {
                return this.DeptNoField;
            }
            set
            {
                this.DeptNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtInfoTypeDefaultCatName
        {
            get
            {
                return this.ExtInfoTypeDefaultCatNameField;
            }
            set
            {
                this.ExtInfoTypeDefaultCatNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtendedInfoTypeDefaultCatID
        {
            get
            {
                return this.ExtendedInfoTypeDefaultCatIDField;
            }
            set
            {
                this.ExtendedInfoTypeDefaultCatIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NominalID
        {
            get
            {
                return this.NominalIDField;
            }
            set
            {
                this.NominalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkCatID
        {
            get
            {
                return this.WorkCatIDField;
            }
            set
            {
                this.WorkCatIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeArchived
        {
            get
            {
                return this.WorkTypeArchivedField;
            }
            set
            {
                this.WorkTypeArchivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeCode
        {
            get
            {
                return this.WorkTypeCodeField;
            }
            set
            {
                this.WorkTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkTypeDept
        {
            get
            {
                return this.WorkTypeDeptField;
            }
            set
            {
                this.WorkTypeDeptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeDescription
        {
            get
            {
                return this.WorkTypeDescriptionField;
            }
            set
            {
                this.WorkTypeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeDisbLimit
        {
            get
            {
                return this.WorkTypeDisbLimitField;
            }
            set
            {
                this.WorkTypeDisbLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WorkTypeID
        {
            get
            {
                return this.WorkTypeIDField;
            }
            set
            {
                this.WorkTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeIsLA
        {
            get
            {
                return this.WorkTypeIsLAField;
            }
            set
            {
                this.WorkTypeIsLAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeOverallLimit
        {
            get
            {
                return this.WorkTypeOverallLimitField;
            }
            set
            {
                this.WorkTypeOverallLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeQuote
        {
            get
            {
                return this.WorkTypeQuoteField;
            }
            set
            {
                this.WorkTypeQuoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeTimeLimit
        {
            get
            {
                return this.WorkTypeTimeLimitField;
            }
            set
            {
                this.WorkTypeTimeLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkTypeWipLimit
        {
            get
            {
                return this.WorkTypeWipLimitField;
            }
            set
            {
                this.WorkTypeWipLimitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSearchItem", Namespace="http://schemas.datacontract.org/2004/07/IRIS.Law.WebServiceInterfaces.Utilities")]
    public partial class UserSearchItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ForenameField;
        
        private string SurnameField;
        
        private int UserIdField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Forename
        {
            get
            {
                return this.ForenameField;
            }
            set
            {
                this.ForenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iris.co.uk/ILB/UtilitiesService", ConfigurationName="IUtilitiesService", SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IUtilitiesService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/UserSearch", ReplyAction="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/UserSearchResponse")]
    IRIS.Law.WebServiceInterfaces.Utilities.UserSearchReturnValue UserSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Utilities.UserSearchCriteria criteria);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/GetMultipleUserDetai" +
        "ls", ReplyAction="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/GetMultipleUserDetai" +
        "lsResponse")]
    IRIS.Law.WebServiceInterfaces.Utilities.UserSearchReturnValue GetMultipleUserDetails(System.Guid logonId, int[] UserIds);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/GetUser", ReplyAction="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/GetUserResponse")]
    IRIS.Law.WebServiceInterfaces.Utilities.UserReturnValue GetUser(System.Guid logonId, System.Guid memberId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/GetWorkType", ReplyAction="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/GetWorkTypeResponse")]
    IRIS.Law.WebServiceInterfaces.Utilities.WorkTypeReturnValue GetWorkType(System.Guid logonId, System.Guid workTypeId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/GetDBVersion", ReplyAction="http://www.iris.co.uk/ILB/UtilitiesService/IUtilitiesService/GetDBVersionResponse" +
        "")]
    IRIS.Law.WebServiceInterfaces.Utilities.DBVersionReturnValue GetDBVersion(System.Guid logonId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUtilitiesServiceChannel : IUtilitiesService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UtilitiesServiceClient : System.ServiceModel.ClientBase<IUtilitiesService>, IUtilitiesService
{
    
    public UtilitiesServiceClient()
    {
    }
    
    public UtilitiesServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UtilitiesServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UtilitiesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UtilitiesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public IRIS.Law.WebServiceInterfaces.Utilities.UserSearchReturnValue UserSearch(System.Guid logonId, IRIS.Law.WebServiceInterfaces.CollectionRequest collectionRequest, IRIS.Law.WebServiceInterfaces.Utilities.UserSearchCriteria criteria)
    {
        return base.Channel.UserSearch(logonId, collectionRequest, criteria);
    }
    
    public IRIS.Law.WebServiceInterfaces.Utilities.UserSearchReturnValue GetMultipleUserDetails(System.Guid logonId, int[] UserIds)
    {
        return base.Channel.GetMultipleUserDetails(logonId, UserIds);
    }
    
    public IRIS.Law.WebServiceInterfaces.Utilities.UserReturnValue GetUser(System.Guid logonId, System.Guid memberId)
    {
        return base.Channel.GetUser(logonId, memberId);
    }
    
    public IRIS.Law.WebServiceInterfaces.Utilities.WorkTypeReturnValue GetWorkType(System.Guid logonId, System.Guid workTypeId)
    {
        return base.Channel.GetWorkType(logonId, workTypeId);
    }
    
    public IRIS.Law.WebServiceInterfaces.Utilities.DBVersionReturnValue GetDBVersion(System.Guid logonId)
    {
        return base.Channel.GetDBVersion(logonId);
    }
}
